/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Sync
         * @description Create or update a user row from a validated Stack Auth JWT + birth_date.
         *
         *     Steps:
         *     1. Validate JWT -> extract sub, email, name.
         *     2. Validate age constraints server-side.
         *     3. Upsert user: CREATE sets role='estudiante', status='nuevo'.
         *        UPDATE only refreshes email + full_name (role change requires admin endpoint).
         */
        post: operations["auth_sync_api_v1_auth_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the current user's public profile.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Stateless logout — Stack Auth manages the session client-side.
         */
        post: operations["logout_api_v1_auth_me_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_v1_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Detail */
        get: operations["get_course_detail_api_v1_courses__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{slug}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll Course */
        post: operations["enroll_course_api_v1_courses__slug__enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{slug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Progress */
        get: operations["get_course_progress_api_v1_courses__slug__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic */
        get: operations["get_topic_api_v1_topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Topic Heartbeat */
        post: operations["topic_heartbeat_api_v1_topics__topic_id__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}/mark-content-done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Content Done */
        post: operations["mark_content_done_api_v1_topics__topic_id__mark_content_done_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}/exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic Exam */
        get: operations["get_topic_exam_api_v1_topics__topic_id__exam_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}/exam/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Topic Exam */
        post: operations["submit_topic_exam_api_v1_topics__topic_id__exam_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{module_id}/exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Module Exam */
        get: operations["get_module_exam_api_v1_modules__module_id__exam_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/{module_id}/exam/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Module Exam */
        post: operations["submit_module_exam_api_v1_modules__module_id__exam_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me Alias */
        get: operations["me_alias_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Alias */
        post: operations["logout_alias_api_v1_me_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_v1_admin_courses_get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_api_v1_admin_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_api_v1_admin_courses__course_id__get"];
        put?: never;
        post?: never;
        /** Delete Course */
        delete: operations["delete_course_api_v1_admin_courses__course_id__delete"];
        options?: never;
        head?: never;
        /** Patch Course */
        patch: operations["patch_course_api_v1_admin_courses__course_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/courses/{course_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Course */
        post: operations["publish_course_api_v1_admin_courses__course_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses/{course_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Course */
        post: operations["archive_course_api_v1_admin_courses__course_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses/{course_id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Module */
        post: operations["create_module_api_v1_admin_courses__course_id__modules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Module */
        delete: operations["delete_module_api_v1_admin_modules__module_id__delete"];
        options?: never;
        head?: never;
        /** Patch Module */
        patch: operations["patch_module_api_v1_admin_modules__module_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/modules/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Modules */
        post: operations["reorder_modules_api_v1_admin_modules_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/modules/{module_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Topic */
        post: operations["create_topic_api_v1_admin_modules__module_id__topics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Topic
         * @description R-ADM-03: Topics with student progress cannot be deleted.
         */
        delete: operations["delete_topic_api_v1_admin_topics__topic_id__delete"];
        options?: never;
        head?: never;
        /** Patch Topic */
        patch: operations["patch_topic_api_v1_admin_topics__topic_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/topics/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Topics */
        post: operations["reorder_topics_api_v1_admin_topics_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics/{topic_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Question For Topic */
        post: operations["create_question_for_topic_api_v1_admin_topics__topic_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/modules/{module_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Question For Module */
        post: operations["create_question_for_module_api_v1_admin_modules__module_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Archive Question
         * @description R-ADM-04: Soft-delete via archived_at. Historical attempts unaffected.
         */
        delete: operations["archive_question_api_v1_admin_questions__question_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Question
         * @description R-ADM-04: Editing enunciado does not affect historical exam_attempts scores.
         */
        patch: operations["patch_question_api_v1_admin_questions__question_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/options/{option_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Option */
        patch: operations["patch_option_api_v1_admin_options__option_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_api_v1_admin_students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student */
        get: operations["get_student_api_v1_admin_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report */
        get: operations["export_report_api_v1_admin_reports_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports/topic-pass-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic Pass Rate */
        get: operations["topic_pass_rate_api_v1_admin_reports_topic_pass_rate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificates/issue/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emit or retrieve a certificate for the authenticated user
         * @description Idempotent: returns the existing certificate if already issued. Returns 422 with code='course_incomplete' if the user has not completed the course.
         */
        post: operations["issue_certificate_endpoint_api_v1_certificates_issue__course_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificates/{public_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get certificate metadata by public UUID (auth optional) */
        get: operations["get_certificate_api_v1_certificates__public_uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificates/{public_uuid}/refresh-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Refresh student name snapshot to current user.full_name (owner only)
         * @description R-CERT-04 resolution: PRD frontend says name should reflect 'momento de descarga'. The certificate is issued with a snapshot. The frontend calls this endpoint immediately before displaying or sharing to sync the snapshot with the user's current full_name. Only the certificate owner may call this.
         */
        patch: operations["refresh_certificate_name_api_v1_certificates__public_uuid__refresh_name_patch"];
        trace?: never;
    };
    "/api/v1/media/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a presigned PUT URL for R2 upload (admin/instructor only) */
        post: operations["get_upload_url_api_v1_media_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/play-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a short-lived JWT to stream a topic's media via the CF Worker */
        post: operations["get_play_token_api_v1_media_play_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify/{public_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public certificate verification page (no auth, indexable) */
        get: operations["verify_certificate_verify__public_uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerItem */
        AnswerItem: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Option Id
             * Format: uuid
             */
            option_id: string;
        };
        /** CertificatePublic */
        CertificatePublic: {
            /**
             * Public Uuid
             * Format: uuid
             */
            public_uuid: string;
            /** Course Title */
            course_title: string;
            /** Student Name */
            student_name: string;
            /** Issued At */
            issued_at: string;
            /** Verify Url */
            verify_url: string;
        };
        /** CourseAdminListItem */
        CourseAdminListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Short Desc */
            short_desc: string;
            /** Status */
            status: string;
            /** Instructor Id */
            instructor_id: string | null;
            /** Order Index */
            order_index: number;
        };
        /** CourseAdminResponse */
        CourseAdminResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Short Desc */
            short_desc: string;
            /** Long Desc */
            long_desc: string;
            /** Cover Key */
            cover_key: string | null;
            /** Age Min */
            age_min: number | null;
            /** Age Max */
            age_max: number | null;
            /** Order Index */
            order_index: number;
            /** Status */
            status: string;
            /** Instructor Id */
            instructor_id: string | null;
            /**
             * Modules
             * @default []
             */
            modules: components["schemas"]["ModuleAdminItem"][];
        };
        /** CourseCard */
        CourseCard: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Short Desc */
            short_desc: string;
            /** Cover Key */
            cover_key: string | null;
            /** Age Min */
            age_min: number | null;
            /** Age Max */
            age_max: number | null;
            /** Order Index */
            order_index: number;
            /** Status */
            status: string;
        };
        /** CourseCardListResponse */
        CourseCardListResponse: {
            /** Items */
            items: components["schemas"]["CourseCard"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CourseCompletions */
        CourseCompletions: {
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Title */
            title: string;
            /** Completions */
            completions: number;
        };
        /** CourseCreate */
        CourseCreate: {
            /** Title */
            title: string;
            /** Short Desc */
            short_desc: string;
            /**
             * Long Desc
             * @default
             */
            long_desc: string;
            /** Cover Key */
            cover_key?: string | null;
            /**
             * Age Min
             * @default 13
             */
            age_min: number;
            /**
             * Age Max
             * @default 99
             */
            age_max: number;
            /** Slug */
            slug: string;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Instructor Id */
            instructor_id?: string | null;
        };
        /** CourseDetail */
        CourseDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Short Desc */
            short_desc: string;
            /** Long Desc */
            long_desc: string;
            /** Cover Key */
            cover_key: string | null;
            /** Age Min */
            age_min: number | null;
            /** Age Max */
            age_max: number | null;
            /** Order Index */
            order_index: number;
            /** Status */
            status: string;
            /** Modules */
            modules: components["schemas"]["ModuleItem"][];
            /** Enrollment Status */
            enrollment_status: string;
            /** Progress Pct */
            progress_pct: number;
        };
        /** CourseProgressResponse */
        CourseProgressResponse: {
            /** Course Pct */
            course_pct: number;
            /** Modules */
            modules: components["schemas"]["ModuleProgressItem"][];
        };
        /** CourseUpdate */
        CourseUpdate: {
            /** Title */
            title?: string | null;
            /** Short Desc */
            short_desc?: string | null;
            /** Long Desc */
            long_desc?: string | null;
            /** Cover Key */
            cover_key?: string | null;
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Order Index */
            order_index?: number | null;
            /** Instructor Id */
            instructor_id?: string | null;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Total Students */
            total_students: number;
            /** New Students Last 7D */
            new_students_last_7d: number;
            /** Active Courses */
            active_courses: number;
            /** Completion Rate */
            completion_rate: number;
            /** Avg Exam Score */
            avg_exam_score: number;
            /** Stuck Students */
            stuck_students: number;
            /** Enrollments Per Week */
            enrollments_per_week: components["schemas"]["WeeklyEnrollments"][];
            /** Completions Per Course */
            completions_per_course: components["schemas"]["CourseCompletions"][];
        };
        /** EnrollResponse */
        EnrollResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Progress Cached */
            progress_cached: number;
        };
        /** EnrollmentSummary */
        EnrollmentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Progress Cached */
            progress_cached: number;
        };
        /** ExamAttemptSummary */
        ExamAttemptSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Topic Id */
            topic_id: string | null;
            /** Module Id */
            module_id: string | null;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Min Score Snapshot */
            min_score_snapshot: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExamResponse */
        ExamResponse: {
            /** Exam Token */
            exam_token: string;
            /** Questions */
            questions: components["schemas"]["QuestionOut"][];
            /** Min Score */
            min_score: number;
        };
        /** ExamResult */
        ExamResult: {
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Min Score */
            min_score: number;
            /** Message */
            message: string;
        };
        /** ExamSubmitRequest */
        ExamSubmitRequest: {
            /** Exam Token */
            exam_token: string;
            /** Answers */
            answers: components["schemas"]["AnswerItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatRequest */
        HeartbeatRequest: {
            /** Type */
            type: string;
            /** Pos Seconds */
            pos_seconds?: number | null;
            /** Max Seen Pct */
            max_seen_pct?: number | null;
            /** Last Page */
            last_page?: number | null;
            /** Total Pages */
            total_pages?: number | null;
        };
        /** HeartbeatResponse */
        HeartbeatResponse: {
            /** State */
            state: string;
            /** Video Last Pos Seconds */
            video_last_pos_seconds: number;
            /** Video Max Seen Pct */
            video_max_seen_pct: number;
            /** Pdf Last Page */
            pdf_last_page: number;
            /** Pdf Total Pages */
            pdf_total_pages: number | null;
        };
        /** MarkContentDoneResponse */
        MarkContentDoneResponse: {
            /** State */
            state: string;
            /** Content Completed At */
            content_completed_at: string | null;
        };
        /** ModuleAdminItem */
        ModuleAdminItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Order Index */
            order_index: number;
            /** Archived At */
            archived_at?: string | null;
            /**
             * Topics
             * @default []
             */
            topics: components["schemas"]["TopicAdminItem"][];
        };
        /** ModuleCreate */
        ModuleCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Order Index */
            order_index?: number | null;
        };
        /** ModuleItem */
        ModuleItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Order Index */
            order_index: number;
            /** Topics */
            topics: components["schemas"]["ModuleTopicItem"][];
        };
        /** ModuleProgressItem */
        ModuleProgressItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Topics */
            topics: components["schemas"]["TopicStateItem"][];
        };
        /** ModuleResponse */
        ModuleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Order Index */
            order_index: number;
            /** Archived At */
            archived_at?: string | null;
        };
        /** ModuleTopicItem */
        ModuleTopicItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Content Type */
            content_type: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Has Exam */
            has_exam: boolean;
            /** Order Index */
            order_index: number;
        };
        /** ModuleUpdate */
        ModuleUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Order Index */
            order_index?: number | null;
        };
        /** OptionCreate */
        OptionCreate: {
            /** Texto */
            texto: string;
            /**
             * Is Correct
             * @default false
             */
            is_correct: boolean;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
        };
        /** OptionOut */
        OptionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Texto */
            texto: string;
        };
        /** OptionResponse */
        OptionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Texto */
            texto: string;
            /** Is Correct */
            is_correct: boolean;
            /** Order Index */
            order_index: number;
        };
        /** OptionUpdate */
        OptionUpdate: {
            /** Texto */
            texto?: string | null;
            /** Is Correct */
            is_correct?: boolean | null;
            /** Order Index */
            order_index?: number | null;
        };
        /** PlayTokenRequest */
        PlayTokenRequest: {
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** PlayTokenResponse */
        PlayTokenResponse: {
            /** Token */
            token: string;
            /** Media Url */
            media_url: string;
            /** Expires In */
            expires_in: number;
        };
        /** QuestionCreate */
        QuestionCreate: {
            /** Enunciado */
            enunciado: string;
            /** Options */
            options: components["schemas"]["OptionCreate"][];
        };
        /** QuestionOut */
        QuestionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Enunciado */
            enunciado: string;
            /** Options */
            options: components["schemas"]["OptionOut"][];
        };
        /** QuestionResponse */
        QuestionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Topic Id */
            topic_id: string | null;
            /** Module Id */
            module_id: string | null;
            /** Enunciado */
            enunciado: string;
            /** Archived At */
            archived_at?: string | null;
            /**
             * Options
             * @default []
             */
            options: components["schemas"]["OptionResponse"][];
        };
        /** QuestionUpdate */
        QuestionUpdate: {
            /** Enunciado */
            enunciado?: string | null;
        };
        /** ReorderBody */
        ReorderBody: {
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Order */
            order: string[];
        };
        /** StudentDetail */
        StudentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Enrollments
             * @default []
             */
            enrollments: components["schemas"]["EnrollmentSummary"][];
            /**
             * Topic Progress
             * @default []
             */
            topic_progress: components["schemas"]["TopicProgressSummary"][];
            /**
             * Exam Attempts
             * @default []
             */
            exam_attempts: components["schemas"]["ExamAttemptSummary"][];
        };
        /** StudentListItem */
        StudentListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Stuck
             * @default false
             */
            is_stuck: boolean;
        };
        /** StudentListResponse */
        StudentListResponse: {
            /** Items */
            items: components["schemas"]["StudentListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * SyncRequest
         * @description Body for POST /auth/sync.
         *
         *     `role` and `email` are intentionally absent — they come from the JWT only.
         */
        SyncRequest: {
            /** Full Name */
            full_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
        };
        /** TopicAdminItem */
        TopicAdminItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Content Type */
            content_type: string;
            /** Has Exam */
            has_exam: boolean;
            /** Exam Min Score */
            exam_min_score: number;
            /** Order Index */
            order_index: number;
            /** Archived At */
            archived_at?: string | null;
        };
        /** TopicCreate */
        TopicCreate: {
            /** Title */
            title: string;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "video" | "pdf" | "imagen" | "texto" | "audio";
            /** Content Body */
            content_body?: string | null;
            /** Media Key */
            media_key?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Has Exam
             * @default true
             */
            has_exam: boolean;
            /**
             * Exam Min Score
             * @default 70
             */
            exam_min_score: number;
            /** Order Index */
            order_index?: number | null;
        };
        /** TopicProgressDetail */
        TopicProgressDetail: {
            /** Video Last Pos Seconds */
            video_last_pos_seconds: number;
            /** Video Max Seen Pct */
            video_max_seen_pct: number;
            /** Pdf Last Page */
            pdf_last_page: number;
            /** Pdf Total Pages */
            pdf_total_pages: number | null;
        };
        /** TopicProgressSummary */
        TopicProgressSummary: {
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /** State */
            state: string;
            /** Video Max Seen Pct */
            video_max_seen_pct: number;
            /** Content Completed At */
            content_completed_at: string | null;
        };
        /** TopicReorderBody */
        TopicReorderBody: {
            /**
             * Module Id
             * Format: uuid
             */
            module_id: string;
            /** Order */
            order: string[];
        };
        /** TopicResponse */
        TopicResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Module Id
             * Format: uuid
             */
            module_id: string;
            /** Title */
            title: string;
            /** Content Type */
            content_type: string;
            /** Content Body */
            content_body: string | null;
            /** Media Key */
            media_key: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Has Exam */
            has_exam: boolean;
            /** Exam Min Score */
            exam_min_score: number;
            /** Order Index */
            order_index: number;
            /** Archived At */
            archived_at?: string | null;
        };
        /** TopicStateItem */
        TopicStateItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** State */
            state: string;
        };
        /** TopicUpdate */
        TopicUpdate: {
            /** Title */
            title?: string | null;
            /** Content Type */
            content_type?: ("video" | "pdf" | "imagen" | "texto" | "audio") | null;
            /** Content Body */
            content_body?: string | null;
            /** Media Key */
            media_key?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Has Exam */
            has_exam?: boolean | null;
            /** Exam Min Score */
            exam_min_score?: number | null;
            /** Order Index */
            order_index?: number | null;
        };
        /** TopicView */
        TopicView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Content Type */
            content_type: string;
            /** Content Body */
            content_body: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Has Exam */
            has_exam: boolean;
            /** Exam Min Score */
            exam_min_score: number;
            /** State */
            state: string;
            progress: components["schemas"]["TopicProgressDetail"];
        };
        /** UploadUrlRequest */
        UploadUrlRequest: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "video" | "pdf" | "imagen" | "cover" | "audio";
        };
        /** UploadUrlResponse */
        UploadUrlResponse: {
            /** Put Url */
            put_url: string;
            /** Key */
            key: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * UserPublic
         * @description Safe public representation of a user — no sensitive internals exposed.
         */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyEnrollments */
        WeeklyEnrollments: {
            /** Week Start */
            week_start: string;
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_sync_api_v1_auth_sync_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_me_logout_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_v1_courses_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseCardListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_detail_api_v1_courses__slug__get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_course_api_v1_courses__slug__enroll_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_progress_api_v1_courses__slug__progress_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_api_v1_topics__topic_id__get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_heartbeat_api_v1_topics__topic_id__heartbeat_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_content_done_api_v1_topics__topic_id__mark_content_done_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkContentDoneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_exam_api_v1_topics__topic_id__exam_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_topic_exam_api_v1_topics__topic_id__exam_submit_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_module_exam_api_v1_modules__module_id__exam_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_module_exam_api_v1_modules__module_id__exam_submit_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_alias_api_v1_me_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_alias_api_v1_me_logout_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_v1_admin_courses_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdminListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_course_api_v1_admin_courses_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdminResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_v1_admin_courses__course_id__get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdminResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_course_api_v1_admin_courses__course_id__delete: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_course_api_v1_admin_courses__course_id__patch: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdminResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_course_api_v1_admin_courses__course_id__publish_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdminResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_course_api_v1_admin_courses__course_id__archive_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdminResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_module_api_v1_admin_courses__course_id__modules_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_module_api_v1_admin_modules__module_id__delete: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_module_api_v1_admin_modules__module_id__patch: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_modules_api_v1_admin_modules_reorder_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_topic_api_v1_admin_modules__module_id__topics_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_topic_api_v1_admin_topics__topic_id__delete: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_topic_api_v1_admin_topics__topic_id__patch: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_topics_api_v1_admin_topics_reorder_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicReorderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_for_topic_api_v1_admin_topics__topic_id__questions_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_for_module_api_v1_admin_modules__module_id__questions_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_question_api_v1_admin_questions__question_id__delete: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_question_api_v1_admin_questions__question_id__patch: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_option_api_v1_admin_options__option_id__patch: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                option_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_students_api_v1_admin_students_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_api_v1_admin_students__student_id__get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_v1_admin_reports_export_get: {
        parameters: {
            query: {
                type: "enrollments" | "completions" | "exam_attempts";
            };
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_pass_rate_api_v1_admin_reports_topic_pass_rate_get: {
        parameters: {
            query: {
                course_id: string;
            };
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_admin_dashboard_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_certificate_endpoint_api_v1_certificates_issue__course_id__post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificatePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_certificate_api_v1_certificates__public_uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificatePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_certificate_name_api_v1_certificates__public_uuid__refresh_name_patch: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                public_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificatePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_url_api_v1_media_upload_url_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_play_token_api_v1_media_play_token_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_certificate_verify__public_uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
